version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    build: ./backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"